Document: gwp
Title: Debian gwp Manual
Author: <insert document author here>
Abstract: This manual describes what gwp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gwp/gwp.sgml.gz

Format: postscript
Files: /usr/share/doc/gwp/gwp.ps.gz

Format: text
Files: /usr/share/doc/gwp/gwp.text.gz

Format: HTML
Index: /usr/share/doc/gwp/html/index.html
Files: /usr/share/doc/gwp/html/*.html

  
